//we can delete parent table without deleting child table by using CASCADE CONSTRAINTS;

DROP TABLE PERSON CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;




CREATE TABLE PERSON(ID NUMBER UNIQUE, NAME VARCHAR2(90), AGE NUMBER);

INSERT INTO PERSON VALUES(1, 'RAMU',22);
INSERT INTO PERSON VALUES(2, 'MANU',24);
INSERT INTO PERSON VALUES(3, 'KIRAN',25);
INSERT INTO PERSON VALUES(4, 'ANU',32);

CREATE TABLE ADDRESS(HOUSE_NO VARCHAR2(90), STREET_NAME VARCHAR2(90), PERSON_ID NUMBER UNIQUE,
                    CONSTRAINT ADDRESS_FK1 FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID));
                    
INSERT INTO ADDRESS VALUES('123/B', 'BTM', 1); 
//FOR ONE PERSON ONLY ONE ADDRESS IS ALLOWED

INSERT INTO ADDRESS VALUES('123/C', 'BTM', 2);
INSERT INTO ADDRESS VALUES('123/D', 'BTM', 3);
INSERT INTO ADDRESS(HOUSE_NO, STREET_NAME) VALUES('123/E', 'BTM');

SELECT * FROM ADDRESS WHERE PERSON_ID = (SELECT ID FROM PERSON WHERE NAME = 'RAMU');

SELECT * FROM PERSON WHERE ID = (SELECT PERSON_ID FROM ADDRESS WHERE HOUSE_NO = '123/C');

SELECT * FROM PERSON, ADDRESS WHERE PERSON.ID = ADDRESS.PERSON_ID;(INNER JOIN)
//DEFAULT JOIN Is INNER JOIN
//WHILE USING JOIN WE HAVE TO SPECIFY 'ON' BUT NOT WHERE


SELECT * FROM PERSON INNER JOIN ADDRESS ON PERSON.ID = ADDRESS.PERSON_ID;

SELECT * FROM PERSON P INNER JOIN ADDRESS A ON P.ID = A.PERSON_ID;

SELECT * FROM PERSON P LEFT OUTER JOIN ADDRESS A ON P.ID = A.PERSON_ID;
SELECT * FROM PERSON P RIGHT OUTER JOIN ADDRESS A ON P.ID = A.PERSON_ID;
SELECT * FROM PERSON P FULL OUTER JOIN ADDRESS A ON P.ID = A.PERSON_ID;
//FULL OUTER JOIN = COMBINATION OF LEFT OUTER AND RIGHT OUTER

//FOREIGN KEY SHOULD NOT BE UNIQUE

CREATE TABLE BOOK(TITLE VARCHAR2(90), PAGES NUMBER, AUTHOR_ID NUMBER, 
            CONSTRAINT BOOK_FK1 FOREIGN KEY(AUTHOR_ID) REFERENCES PERSON(ID));

                    
INSERT INTO BOOK VALUES('JAVA MADE EASY', 1000, 1);
INSERT INTO BOOK VALUES('SQL MADE EASY', 500, 1);
INSERT INTO BOOK VALUES('HTML MADE EASY', 200, 2);
INSERT INTO BOOK VALUES('SERVLETS MADE EASY', 700, 2);
INSERT INTO BOOK VALUES('JSP MADE EASY', 700, 2);
INSERT INTO BOOK VALUES('J2EE MADE EASY', 1200, 4);
INSERT INTO BOOK(TITLE, PAGES)VALUES('HADOOP MADE EASY', 500);

SELECT ID FROM PERSON WHERE NAME ='RAMU';
SELECT * FROM BOOK WHERE AUTHOR_ID IN (SELECT ID FROM PERSON WHERE NAME ='RAMU');

SELECT NAME FROM PERSON WHERE ID = (SELECT AUTHOR_ID FROM BOOK WHERE TITLE = 'J2EE MADE EASY');

SELECT * FROM PERSON P INNER JOIN BOOK B ON P.ID = B.AUTHOR_ID;

SELECT * FROM PERSON P LEFT OUTER JOIN BOOK B ON P.ID = B.AUTHOR_ID;

SELECT * FROM PERSON P RIGHT OUTER JOIN BOOK B ON P.ID = B.AUTHOR_ID; 

SELECT * FROM PERSON P FULL OUTER JOIN BOOK B ON P.ID = B.AUTHOR_ID;

