//package pack1;
enum A
{
	void test()
	{
	}
	// for enum also genrating  while compling
}

/* javac -d ../classes pack1/A.java
*/
// ENUMS ARE USED IN JDK1.5
// ENUM CAN BECOMING A JAVA FILE LIKE CLASS ,INTERFACE
// WILL COMPLING CLS FILE GENERATING TO ENUM ALSO
// ENUMS ARE MANILY FOR GROUPING SIMILAR KIND OF FIXED NUMBER OF ORDER CONSTANTS
// EVERY CONSTANT SHOULD REPRESENTED THROUGH  VALIED JAVA IDENTIFIER 
// ALL THE CONSTANTS SHOULD BE UNIQUE
// EVERY CONSTANT SHOULD BE SAPARATED WITH ',' AS A SAPARATOR
// EVERY CONSTANT HAVE A UNIQUE INDEX STATRING WITH '0'
// INSIDE A ENUM NOT ONLY CONSTANTS WE CAN INCORPPORATE ATRIBUTES CONSTRUCTORS AND METHODS
// ENUM CAN BECOME A MUMBER OF THE CLASS 
// INSIDE A CLASS WE CAN DEVELOP A ENUM
// ENUM IS COMING UNDER DERIVED DATA TYPE
